"""empty message

Revision ID: 0b639050314d
Revises: 640624ee18ba
Create Date: 2018-01-15 12:20:55.171486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b639050314d'
down_revision = '640624ee18ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EventFrameTemplate', 'ElementTemplateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint('AK__ElementTemplateId_Name', 'EventFrameTemplate', ['ElementTemplateId', 'Name'])
    op.create_unique_constraint('AK__Name_ParentEventFrameTemplateId', 'EventFrameTemplate', ['Name', 'ParentEventFrameTemplateId'])
    op.create_unique_constraint('AK__Order_ParentEventFrameTemplateId', 'EventFrameTemplate', ['Order', 'ParentEventFrameTemplateId'])
    op.drop_index('AK__ElementTemplateId_Name_Order_ParentEventFrameTemplateId', table_name='EventFrameTemplate')
    op.alter_column('EventFrame', 'EndTime', existing_type=sa.DateTime(), new_column_name='EndTimestamp')
    op.alter_column('EventFrame', 'StartTime', existing_type=sa.DateTime(), new_column_name='StartTimestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('AK__ElementTemplateId_Name_Order_ParentEventFrameTemplateId', 'EventFrameTemplate', ['ElementTemplateId', 'Name', 'Order', 'ParentEventFrameTemplateId'], unique=True)
    op.drop_constraint('AK__Order_ParentEventFrameTemplateId', 'EventFrameTemplate', type_='unique')
    op.drop_constraint('AK__Name_ParentEventFrameTemplateId', 'EventFrameTemplate', type_='unique')
    op.drop_constraint('AK__ElementTemplateId_Name', 'EventFrameTemplate', type_='unique')
    op.alter_column('EventFrameTemplate', 'ElementTemplateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('EventFrame', 'StartTimestamp', existing_type=sa.DateTime(), new_column_name='StartTime')
    op.alter_column('EventFrame', 'EndTimestamp', existing_type=sa.DateTime(), new_column_name='EndTime')
    # ### end Alembic commands ###
