"""Dictionary column.

Revision ID: 0d51971e2c1c
Revises: 6a46aedc29fc
Create Date: 2020-02-27 01:21:09.830183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d51971e2c1c'
down_revision = '6a46aedc29fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameTemplateView', sa.Column('Dictionary', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventFrameTemplateView', 'Dictionary')
    # ### end Alembic commands ###
