"""empty message

Revision ID: 168c0a35351e
Revises: 69206798fe36
Create Date: 2018-06-11 19:32:00.295551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '168c0a35351e'
down_revision = '69206798fe36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameAttribute', sa.Column('ElementId', sa.Integer(), nullable=False))
    op.create_unique_constraint('AK__EventFrameAttributeTemplateId__ElementId', 'EventFrameAttribute', ['EventFrameAttributeTemplateId', 'ElementId'])
    op.drop_index('AK__EventFrameAttributeTemplateId__EventFrameId', table_name='EventFrameAttribute')
    op.drop_constraint('FK__EventFrame$Have$EventFrameAttribute', 'EventFrameAttribute', type_='foreignkey')
    op.create_foreign_key('FK__Element$Have$EventFrameAttribute', 'EventFrameAttribute', 'Element', ['ElementId'], ['ElementId'])
    op.drop_column('EventFrameAttribute', 'EventFrameId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameAttribute', sa.Column('EventFrameId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint('FK__Element$Have$EventFrameAttribute', 'EventFrameAttribute', type_='foreignkey')
    op.create_foreign_key('FK__EventFrame$Have$EventFrameAttribute', 'EventFrameAttribute', 'EventFrame', ['EventFrameId'], ['EventFrameId'])
    op.create_index('AK__EventFrameAttributeTemplateId__EventFrameId', 'EventFrameAttribute', ['EventFrameAttributeTemplateId', 'EventFrameId'], unique=True)
    op.drop_constraint('AK__EventFrameAttributeTemplateId__ElementId', 'EventFrameAttribute', type_='unique')
    op.drop_column('EventFrameAttribute', 'ElementId')
    # ### end Alembic commands ###
