"""empty message

Revision ID: 1eb5be1d5f50
Revises: e3249c6eab5c
Create Date: 2019-03-13 23:01:22.106946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb5be1d5f50'
down_revision = 'e3249c6eab5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('UserId', sa.Integer(), nullable=False))
    op.create_foreign_key('FK__User$AddOrEdit$EventFrame', 'EventFrame', 'User', ['UserId'], ['UserId'])
    op.add_column('Note', sa.Column('UserId', sa.Integer(), nullable=False))
    op.create_foreign_key('FK__User$AddOrEdit$Note', 'Note', 'User', ['UserId'], ['UserId'])
    op.add_column('TagValue', sa.Column('UserId', sa.Integer(), nullable=False))
    op.create_foreign_key('FK__User$AddOrEdit$TagValue', 'TagValue', 'User', ['UserId'], ['UserId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__User$AddOrEdit$TagValue', 'TagValue', type_='foreignkey')
    op.drop_column('TagValue', 'UserId')
    op.drop_constraint('FK__User$AddOrEdit$Note', 'Note', type_='foreignkey')
    op.drop_column('Note', 'UserId')
    op.drop_constraint('FK__User$AddOrEdit$EventFrame', 'EventFrame', type_='foreignkey')
    op.drop_column('EventFrame', 'UserId')
    # ### end Alembic commands ###
