"""empty message

Revision ID: 2508aaaa18ea
Revises: 640624ee18ba
Create Date: 2018-01-20 10:59:30.873362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2508aaaa18ea'
down_revision = '640624ee18ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('EndTimestamp', sa.DateTime(), nullable=True))
    op.add_column('EventFrame', sa.Column('StartTimestamp', sa.DateTime(), nullable=False))
    op.create_unique_constraint('AK__ElementId_EventFrameTemplateId_StartTimestamp', 'EventFrame', ['ElementId', 'EventFrameTemplateId', 'StartTimestamp'])
    op.drop_index('AK__ElementId_EventFrameTemplateId_StartTime', table_name='EventFrame')
    op.drop_column('EventFrame', 'EndTime')
    op.drop_column('EventFrame', 'StartTime')
    op.alter_column('EventFrameTemplate', 'ElementTemplateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint('AK__ElementTemplateId_Name', 'EventFrameTemplate', ['ElementTemplateId', 'Name'])
    op.create_unique_constraint('AK__Name_ParentEventFrameTemplateId', 'EventFrameTemplate', ['Name', 'ParentEventFrameTemplateId'])
    op.create_unique_constraint('AK__Order_ParentEventFrameTemplateId', 'EventFrameTemplate', ['Order', 'ParentEventFrameTemplateId'])
    op.drop_index('AK__ElementTemplateId_Name_Order_ParentEventFrameTemplateId', table_name='EventFrameTemplate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('AK__ElementTemplateId_Name_Order_ParentEventFrameTemplateId', 'EventFrameTemplate', ['ElementTemplateId', 'Name', 'Order', 'ParentEventFrameTemplateId'], unique=True)
    op.drop_constraint('AK__Order_ParentEventFrameTemplateId', 'EventFrameTemplate', type_='unique')
    op.drop_constraint('AK__Name_ParentEventFrameTemplateId', 'EventFrameTemplate', type_='unique')
    op.drop_constraint('AK__ElementTemplateId_Name', 'EventFrameTemplate', type_='unique')
    op.alter_column('EventFrameTemplate', 'ElementTemplateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('EventFrame', sa.Column('StartTime', mysql.DATETIME(), nullable=False))
    op.add_column('EventFrame', sa.Column('EndTime', mysql.DATETIME(), nullable=True))
    op.create_index('AK__ElementId_EventFrameTemplateId_StartTime', 'EventFrame', ['ElementId', 'EventFrameTemplateId', 'StartTime'], unique=True)
    op.drop_constraint('AK__ElementId_EventFrameTemplateId_StartTimestamp', 'EventFrame', type_='unique')
    op.drop_column('EventFrame', 'StartTimestamp')
    op.drop_column('EventFrame', 'EndTimestamp')
    # ### end Alembic commands ###
