"""empty message

Revision ID: 28b15eb180a4
Revises: 7e411683509e
Create Date: 2018-03-07 16:19:37.869441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b15eb180a4'
down_revision = '7e411683509e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Note',
    sa.Column('NoteId', sa.Integer(), nullable=False),
    sa.Column('Note', sa.Text(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('NoteId')
    )
    op.create_index(op.f('ix_Note_Timestamp'), 'Note', ['Timestamp'], unique=False)
    op.create_table('EventFrameNote',
    sa.Column('NoteId', sa.Integer(), nullable=False),
    sa.Column('EventFrameId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EventFrameId'], ['EventFrame.EventFrameId'], name='FK__EventFrame$CanHave$EventFrameNote'),
    sa.ForeignKeyConstraint(['NoteId'], ['Note.NoteId'], name='FK__Note$CanBe$EventFrameNote'),
    sa.PrimaryKeyConstraint('NoteId', 'EventFrameId')
    )
    op.create_table('TagValueNote',
    sa.Column('NoteId', sa.Integer(), nullable=False),
    sa.Column('TagValueId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NoteId'], ['Note.NoteId'], name='FK__Note$CanBe$TagValueNote'),
    sa.ForeignKeyConstraint(['TagValueId'], ['TagValue.TagValueId'], name='FK__TagValue$CanHave$TagValueNote'),
    sa.PrimaryKeyConstraint('NoteId', 'TagValueId')
    )
    # op.create_index(op.f('ix_TagValue_Timestamp'), 'TagValue', ['Timestamp'], unique=False)
    # op.drop_index('ix_TagValue_Timestamp', table_name='TagValue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_TagValue_Timestamp', 'TagValue', ['Timestamp'], unique=False)
    # op.drop_index(op.f('ix_TagValue_Timestamp'), table_name='TagValue')
    op.drop_table('TagValueNote')
    op.drop_table('EventFrameNote')
    op.drop_index(op.f('ix_Note_Timestamp'), table_name='Note')
    op.drop_table('Note')
    # ### end Alembic commands ###
