"""Event Frame Template View Order.

Revision ID: 298f8690d1d7
Revises: b13236977763
Create Date: 2020-08-16 17:13:18.236999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.dialects import mysql
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class EventFrameTemplate(Base):
	__tablename__ = "EventFrameTemplate"

	EventFrameTemplateId = sa.Column(sa.Integer, primary_key = True)

	EventFrameTemplateViews = orm.relationship("EventFrameTemplateView", backref = "EventFrameTemplate", lazy = "dynamic")

class EventFrameTemplateView(Base):
	__tablename__ = "EventFrameTemplateView"

	EventFrameTemplateViewId = sa.Column(sa.Integer, primary_key = True)
	EventFrameTemplateId = sa.Column(sa.Integer, sa.ForeignKey("EventFrameTemplate.EventFrameTemplateId"), nullable = False)
	Name = sa.Column(sa.String(45), nullable = False)
	Order = sa.Column(sa.Integer, nullable = True)

# revision identifiers, used by Alembic.
revision = '298f8690d1d7'
down_revision = 'b13236977763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameTemplateView', sa.Column('Order', sa.Integer(), nullable=True))
    metadata = sa.MetaData()
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for eventFrameTemplate in session.query(EventFrameTemplate):
        for i, eventFrameTemplateView in enumerate(eventFrameTemplate.EventFrameTemplateViews.order_by(EventFrameTemplateView.Name), 1):
            eventFrameTemplateView.Order = i

    session.commit()
    op.alter_column('EventFrameTemplateView', 'Order', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.create_unique_constraint('AK__EventFrameTemplateViewId__Order', 'EventFrameTemplateView', ['EventFrameTemplateViewId', 'Order'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AK__EventFrameTemplateViewId__Order', 'EventFrameTemplateView', type_='unique')
    op.drop_column('EventFrameTemplateView', 'Order')
    # ### end Alembic commands ###
