"""Event Frame Genealogy.

Revision ID: 5615319f05e3
Revises: b13236977763
Create Date: 2020-07-29 14:07:06.026260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5615319f05e3'
down_revision = 'b13236977763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('SourceEventFrameId', sa.Integer(), nullable=True))
    op.create_foreign_key('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', 'EventFrame', ['SourceEventFrameId'], ['EventFrameId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', type_='foreignkey')
    op.drop_column('EventFrame', 'SourceEventFrameId')
    # ### end Alembic commands ###
