"""Removed SourceEventFrameTemplate

Revision ID: 56dc6d818b34
Revises: 61a639465246
Create Date: 2020-03-09 12:50:27.811661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56dc6d818b34'
down_revision = '61a639465246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__EventFrameTemplate$CanHave$SourceEventFrameTemplate', 'EventFrameTemplate', type_='foreignkey')
    op.drop_column('EventFrameTemplate', 'SourceEventFrameTemplateId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameTemplate', sa.Column('SourceEventFrameTemplateId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__EventFrameTemplate$CanHave$SourceEventFrameTemplate', 'EventFrameTemplate', 'EventFrameTemplate', ['SourceEventFrameTemplateId'], ['EventFrameTemplateId'])
    # ### end Alembic commands ###
