"""empty message

Revision ID: 5b51435f491a
Revises: f64c7735ec58
Create Date: 2018-05-15 12:18:14.514388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b51435f491a'
down_revision = 'f64c7735ec58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ElementAttributeTemplate',
    sa.Column('ElementAttributeTemplateId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('ElementTemplateId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], name='FK__ElementTemplate$Have$ElementAttributeTemplate'),
    sa.PrimaryKeyConstraint('ElementAttributeTemplateId'),
    sa.UniqueConstraint('ElementTemplateId', 'Name', name='AK__ElementTemplateId__Name')
    )
    op.add_column('ElementAttribute', sa.Column('ElementAttributeTemplateId', sa.Integer(), nullable=False))
    op.create_unique_constraint('AK__ElementAttributeTemplateId__ElementId', 'ElementAttribute', ['ElementAttributeTemplateId', 'ElementId'])
    op.drop_constraint('FK__AttributeTemplate$Have$ElementAttribute', 'ElementAttribute', type_='foreignkey')
    op.drop_index('AK__AttributeTemplateId__ElementId', table_name='ElementAttribute')
    op.create_foreign_key('FK__ElementAttributeTemplate$Have$ElementAttribute', 'ElementAttribute', 'ElementAttributeTemplate', ['ElementAttributeTemplateId'], ['ElementAttributeTemplateId'])
    op.drop_column('ElementAttribute', 'AttributeTemplateId')
    op.drop_table('AttributeTemplate')
# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AttributeTemplate',
    sa.Column('AttributeTemplateId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ElementTemplateId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=45), nullable=False),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], name='FK__ElementTemplate$Have$AttributeTemplate'),
    sa.PrimaryKeyConstraint('AttributeTemplateId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column('ElementAttribute', sa.Column('AttributeTemplateId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint('FK__ElementAttributeTemplate$Have$ElementAttribute', 'ElementAttribute', type_='foreignkey')
    op.create_foreign_key('FK__AttributeTemplate$Have$ElementAttribute', 'ElementAttribute', 'AttributeTemplate', ['AttributeTemplateId'], ['AttributeTemplateId'])
    op.create_index('AK__AttributeTemplateId__ElementId', 'ElementAttribute', ['AttributeTemplateId', 'ElementId'], unique=True)
    op.drop_constraint('AK__ElementAttributeTemplateId__ElementId', 'ElementAttribute', type_='unique')
    op.drop_column('ElementAttribute', 'ElementAttributeTemplateId')
    op.create_index('AK__ElementTemplateId__Name', 'AttributeTemplate', ['ElementTemplateId', 'Name'], unique=True)
    op.drop_table('ElementAttributeTemplate')
    # ### end Alembic commands ###
