"""empty message

Revision ID: 5d171bedf234
Revises: 1476a62140ae
Create Date: 2018-02-07 14:50:55.947439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d171bedf234'
down_revision = '1476a62140ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventFrameTemplate',
    sa.Column('EventFrameTemplateId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('ElementTemplateId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('Order', sa.Integer(), nullable=False),
    sa.Column('ParentEventFrameTemplateId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], name='FK__ElementTemplate$Have$EventFrameTemplate'),
    sa.ForeignKeyConstraint(['ParentEventFrameTemplateId'], ['EventFrameTemplate.EventFrameTemplateId'], name='FK__EventFrameTemplate$CanHave$EventFrameTemplate'),
    sa.PrimaryKeyConstraint('EventFrameTemplateId'),
    sa.UniqueConstraint('ElementTemplateId', 'Name', name='AK__ElementTemplateId_Name'),
    sa.UniqueConstraint('Name', 'ParentEventFrameTemplateId', name='AK__Name_ParentEventFrameTemplateId'),
    sa.UniqueConstraint('Order', 'ParentEventFrameTemplateId', name='AK__Order_ParentEventFrameTemplateId')
    )
    op.create_table('EventFrame',
    sa.Column('EventFrameId', sa.Integer(), nullable=False),
    sa.Column('ElementId', sa.Integer(), nullable=True),
    sa.Column('EndTimestamp', sa.DateTime(), nullable=True),
    sa.Column('EventFrameTemplateId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=True),
    sa.Column('ParentEventFrameId', sa.Integer(), nullable=True),
    sa.Column('StartTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ElementId'], ['Element.ElementId'], name='FK__Element$Have$EventFrame'),
    sa.ForeignKeyConstraint(['EventFrameTemplateId'], ['EventFrameTemplate.EventFrameTemplateId'], name='FK__EventFrameTemplate$Have$EventFrame'),
    sa.ForeignKeyConstraint(['ParentEventFrameId'], ['EventFrame.EventFrameId'], name='FK__EventFrame$CanHave$EventFrame'),
    sa.PrimaryKeyConstraint('EventFrameId'),
    sa.UniqueConstraint('ElementId', 'EventFrameTemplateId', 'StartTimestamp', name='AK__ElementId_EventFrameTemplateId_StartTimestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EventFrame')
    op.drop_table('EventFrameTemplate')
    # ### end Alembic commands ###
