"""empty message

Revision ID: 640624ee18ba
Revises: c850b9555b12
Create Date: 2018-01-01 20:32:29.970424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '640624ee18ba'
down_revision = 'c850b9555b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('AK__ElementId_EventFrameTemplateId_StartTime', 'EventFrame', ['ElementId', 'EventFrameTemplateId', 'StartTime'])
    op.drop_index('AK__ElementId_EventFrameTemplateId_Name_StartTime', table_name='EventFrame')
    op.drop_column('EventFrame', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('Description', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('AK__ElementId_EventFrameTemplateId_Name_StartTime', 'EventFrame', ['ElementId', 'EventFrameTemplateId', 'Name', 'StartTime'], unique=True)
    op.drop_constraint('AK__ElementId_EventFrameTemplateId_StartTime', 'EventFrame', type_='unique')
    # ### end Alembic commands ###
