"""Event frame groups.

Revision ID: 693d24be14f4
Revises: 1d0e685b68e0
Create Date: 2019-08-20 21:55:44.976853

"""
from alembic import op
import sqlalchemy as sa
from db.migrations.replaceableObjects import ReplaceableObject


# revision identifiers, used by Alembic.
revision = '693d24be14f4'
down_revision = '1d0e685b68e0'
branch_labels = None
depends_on = None



spEventFrameSummary = ReplaceableObject(
    "spEventFrameSummary",
    "IN eventFrameAttributeTemplateNames TEXT, IN eventFrameIds TEXT",
    None,
    """
BEGIN
	SET @@group_concat_max_len = 5000;
	SET @sql = NULL;
	SET @dynamicColumns = NULL;

	-- Build the column list of event frame attribute values.
	/*
	SELECT GROUP_CONCAT(DISTINCT CONCAT('MAX(IF(EventFrameAttributeTemplate.Name = ''', EventFrameAttributeTemplate.Name, ''', IF(Tag.LookupId IS NULL, TagValue.Value, LookupValue.Name), '''')) AS ''', EventFrameAttributeTemplate.Name, '''')) INTO @dynamicColumns
	FROM EventFrameAttributeTemplate
		INNER JOIN EventFrameTemplate ON EventFrameAttributeTemplate.EventFrameTemplateId = EventFrameTemplate.EventFrameTemplateId
        INNER JOIN EventFrame ON EventFrameTemplate.EventFrameTemplateId = EventFrame.EventFrameTemplateId
    WHERE FIND_IN_SET(EventFrame.EventFrameId, eventFrameIds) > 0;
	*/
	SELECT GROUP_CONCAT(DISTINCT CONCAT('MAX(IF(EventFrameAttributeTemplate.Name = ''', EventFrameAttributeTemplate.Name, ''', IF(Tag.LookupId IS NULL, TagValue.Value, LookupValue.Name), '''')) AS ''', EventFrameAttributeTemplate.Name, '''')) INTO @dynamicColumns
	FROM EventFrameAttributeTemplate
    WHERE FIND_IN_SET(EventFrameAttributeTemplate.Name, eventFrameAttributeTemplateNames) > 0;

	SET @sql = CONCAT('
		SELECT CONCAT(Enterprise.Abbreviation, ''_'', Site.Abbreviation, ''_'', ElementTemplate.Name, ''_'', EventFrameTemplate.Name) AS Template,
			Element.Name AS Element,
			EventFrame.Name,
			EventFrame.StartTimestamp AS Start,
			EventFrame.EndTimestamp AS End,
            ', @dynamicColumns, '
		FROM EventFrame
			INNER JOIN Element ON EventFrame.ElementId = Element.ElementId
			INNER JOIN EventFrameTemplate ON EventFrame.EventFrameTemplateId = EventFrameTemplate.EventFrameTemplateId
            INNER JOIN ElementTemplate ON Element.ElementTemplateId = ElementTemplate.ElementTemplateId
				AND EventFrameTemplate.ElementTemplateId = ElementTemplate.ElementTemplateId
			INNER JOIN Site ON ElementTemplate.SiteId = Site.SiteId
            INNER JOIN Enterprise ON Site.EnterpriseId = Enterprise.EnterpriseId
			LEFT JOIN EventFrameAttributeTemplate ON EventFrameTemplate.EventFrameTemplateId = EventFrameAttributeTemplate.EventFrameTemplateId
			LEFT JOIN EventFrameAttribute ON EventFrameAttributeTemplate.EventFrameAttributeTemplateId = EventFrameAttribute.EventFrameAttributeTemplateId AND
				Element.ElementId = EventFrameAttribute.ElementId
			LEFT JOIN
			(
				SELECT EventFrame.EventFrameId AS EventFrameId,
					EventFrameAttributeTemplate.Name AS EventFrameAttributeTemplateName,
					MAX(TagValue.Timestamp) AS Timestamp
				FROM EventFrame
					INNER JOIN Element ON EventFrame.ElementId = Element.ElementId
					INNER JOIN EventFrameTemplate ON EventFrame.EventFrameTemplateId = EventFrameTemplate.EventFrameTemplateId
					INNER JOIN EventFrameAttributeTemplate ON EventFrameTemplate.EventFrameTemplateId = EventFrameAttributeTemplate.EventFrameTemplateId
					LEFT JOIN EventFrameAttribute ON EventFrameAttributeTemplate.EventFrameAttributeTemplateId = EventFrameAttribute.EventFrameAttributeTemplateId AND
						Element.ElementId = EventFrameAttribute.ElementId
					LEFT JOIN Tag ON EventFrameAttribute.TagId = Tag.TagId
					LEFT JOIN TagValue ON Tag.TagId = TagValue.TagId AND
						CASE
							WHEN EventFrame.EndTimestamp IS NULL THEN
								(TagValue.Timestamp >= EventFrame.StartTimestamp)
							ELSE
								(TagValue.Timestamp >= EventFrame.StartTimestamp AND TagValue.Timestamp <= EventFrame.EndTimestamp)
						END
				WHERE EventFrame.EventFrameId IN (', eventFrameIds, ')
				GROUP BY EventFrameId,
					EventFrameAttributeTemplateName
			) CurrentEventFrameAttributeValue ON EventFrame.EventFrameId = CurrentEventFrameAttributeValue.EventFrameId AND
				EventFrameAttributeTemplate.Name = CurrentEventFrameAttributeValue.EventFrameAttributeTemplateName
			LEFT JOIN Tag ON EventFrameAttribute.TagId = Tag.TagId
			LEFT JOIN TagValue ON Tag.TagId = TagValue.TagId AND
				TagValue.Timestamp = CurrentEventFrameAttributeValue.Timestamp
			LEFT JOIN Lookup ON Tag.LookupId = Lookup.LookupId
			LEFT JOIN LookupValue ON Lookup.LookupId = LookupValue.LookupId AND
				TagValue.Value = LookupValue.Value
		WHERE EventFrame.EventFrameId IN (', eventFrameIds, ')
		GROUP BY EventFrame.EventFrameId
        ORDER BY Template, Element');

	PREPARE stmt FROM @sql;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
END""")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventFrameGroup',
    sa.Column('EventFrameGroupId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('EventFrameGroupId'),
    sa.UniqueConstraint('Name', name='AK__Name')
    )
    op.create_index('IX__Name', 'EventFrameGroup', ['Name'], unique=False)
    op.create_table('EventFrameEventFrameGroup',
    sa.Column('EventFrameEventFrameGroupId', sa.Integer(), nullable=False),
    sa.Column('EventFrameGroupId', sa.Integer(), nullable=False),
    sa.Column('EventFrameId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EventFrameGroupId'], ['EventFrameGroup.EventFrameGroupId'], name='FK__EventFrameGroup$Have$EventFrameEventFrameGroup'),
    sa.ForeignKeyConstraint(['EventFrameId'], ['EventFrame.EventFrameId'], name='FK__EventFrame$Have$EventFrameEventFrameGroup'),
    sa.PrimaryKeyConstraint('EventFrameEventFrameGroupId'),
    sa.UniqueConstraint('EventFrameGroupId', 'EventFrameId', name='AK__EventFrameGroupId__EventFrameId')
    )
    # ### end Alembic commands ###
    op.createStoredProcedure(spEventFrameSummary)


def downgrade():
    op.dropStoredProcedure(spEventFrameSummary)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EventFrameEventFrameGroup')
    op.drop_index('IX__Name', table_name='EventFrameGroup')
    op.drop_table('EventFrameGroup')
    # ### end Alembic commands ###
