"""Added Order column.

Revision ID: 6a46aedc29fc
Revises: 269fed78b4c1
Create Date: 2020-02-24 08:51:37.964685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a46aedc29fc'
down_revision = '269fed78b4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameAttributeTemplateEventFrameTemplateView', sa.Column('Order', sa.Integer(), nullable=False))
    op.create_unique_constraint('AK__EventFrameTemplateViewId__Order', 'EventFrameAttributeTemplateEventFrameTemplateView', ['EventFrameTemplateViewId', 'Order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AK__EventFrameTemplateViewId__Order', 'EventFrameAttributeTemplateEventFrameTemplateView', type_='unique')
    op.drop_column('EventFrameAttributeTemplateEventFrameTemplateView', 'Order')
    # ### end Alembic commands ###
