"""empty message

Revision ID: 78b691c1b20e
Revises: c6770e4b00f9
Create Date: 2019-02-09 09:41:56.673043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b691c1b20e'
down_revision = 'c6770e4b00f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameAttributeTemplate', sa.Column('DefaultEndValue', sa.Float(), nullable=True))
    op.add_column('EventFrameAttributeTemplate', sa.Column('DefaultStartValue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventFrameAttributeTemplate', 'DefaultStartValue')
    op.drop_column('EventFrameAttributeTemplate', 'DefaultEndValue')
    # ### end Alembic commands ###
