"""empty message

Revision ID: 7e411683509e
Revises: 5d171bedf234
Create Date: 2018-03-01 07:50:41.013631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e411683509e'
down_revision = '5d171bedf234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_TagValue_Timestamp'), 'TagValue', ['Timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TagValue_Timestamp'), table_name='TagValue')
    # ### end Alembic commands ###
