"""Event frame template views.

Revision ID: 9704c50cdd4e
Revises: 693d24be14f4
Create Date: 2019-12-26 19:56:16.414113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9704c50cdd4e'
down_revision = '693d24be14f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventFrameAttributeTemplateEventFrameTemplateView',
    sa.Column('EventFrameAttributeTemplateEventFrameTemplateViewId', sa.Integer(), nullable=False),
    sa.Column('EventFrameAttributeTemplateId', sa.Integer(), nullable=False),
    sa.Column('EventFrameTemplateViewId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EventFrameAttributeTemplateId'], ['EventFrameAttributeTemplate.EventFrameAttributeTemplateId'], name='FK__EFAT$Have$EventFrameAttributeTemplateEventFrameTemplateView'),
    sa.ForeignKeyConstraint(['EventFrameTemplateViewId'], ['EventFrameTemplateView.EventFrameTemplateViewId'], name='FK__EFTV$Have$EventFrameAttributeTemplateEventFrameTemplateView'),
    sa.PrimaryKeyConstraint('EventFrameAttributeTemplateEventFrameTemplateViewId'),
    sa.UniqueConstraint('EventFrameAttributeTemplateId', 'EventFrameTemplateViewId', name='AK__EventFrameAttributeTemplateId__EventFrameTemplateViewId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EventFrameAttributeTemplateEventFrameTemplateView')
    # ### end Alembic commands ###
