"""empty message

Revision ID: 9a701cbc3382
Revises: 1eb5be1d5f50
Create Date: 2019-03-14 19:19:27.791976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a701cbc3382'
down_revision = '1eb5be1d5f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'Enabled')
    # ### end Alembic commands ###
