"""Add microseconds to timestamps.

Revision ID: 9b71da09fc0b
Revises: 693d24be14f4
Create Date: 2020-01-03 01:10:30.043225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b71da09fc0b'
down_revision = '693d24be14f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EventFrame', 'EndTimestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('EventFrame', 'StartTimestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('Message', 'Timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('Note', 'Timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('TagValue', 'Timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('User', 'LastMessageReadTimestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
