"""Event Frame genealogy.

Revision ID: a6a42a413d13
Revises: 76cfe6045752
Create Date: 2020-10-11 10:04:23.995351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a42a413d13'
down_revision = '76cfe6045752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('SourceEventFrameId', sa.Integer(), nullable=True))
    op.create_foreign_key('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', 'EventFrame', ['SourceEventFrameId'], ['EventFrameId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', type_='foreignkey')
    op.drop_column('EventFrame', 'SourceEventFrameId')
    # ### end Alembic commands ###
