"""Source Event Frame

Revision ID: aa3bc795f31f
Revises: fa707933be8d
Create Date: 2019-05-30 12:49:07.705631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3bc795f31f'
down_revision = 'fa707933be8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrame', sa.Column('SourceEventFrameId', sa.Integer(), nullable=True))
    op.create_foreign_key('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', 'EventFrame', ['SourceEventFrameId'], ['EventFrameId'])
    op.add_column('EventFrameTemplate', sa.Column('SourceEventFrameTemplateId', sa.Integer(), nullable=True))
    op.create_foreign_key('FK__EventFrameTemplate$CanHave$SourceEventFrameTemplate', 'EventFrameTemplate', 'EventFrameTemplate', ['SourceEventFrameTemplateId'], ['EventFrameTemplateId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__EventFrameTemplate$CanHave$SourceEventFrameTemplate', 'EventFrameTemplate', type_='foreignkey')
    op.drop_column('EventFrameTemplate', 'SourceEventFrameTemplateId')
    op.drop_constraint('FK__EventFrame$CanHave$SourceEventFrame', 'EventFrame', type_='foreignkey')
    op.drop_column('EventFrame', 'SourceEventFrameId')
    # ### end Alembic commands ###
