"""empty message

Revision ID: c6770e4b00f9
Revises: 8d47782a0098
Create Date: 2019-02-05 09:08:01.697962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6770e4b00f9'
down_revision = '8d47782a0098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameAttributeTemplate', sa.Column('LookupId', sa.Integer(), nullable=True))
    op.add_column('EventFrameAttributeTemplate', sa.Column('UnitOfMeasurementId', sa.Integer(), nullable=True))
    op.create_foreign_key('FK__UnitOfMeasurement$CanBeUsedIn$EventFrameAttributeTemplate', 'EventFrameAttributeTemplate', 'UnitOfMeasurement', ['UnitOfMeasurementId'], ['UnitOfMeasurementId'])
    op.create_foreign_key('FK__Lookup$CanBeUsedIn$EventFrameAttributeTemplate', 'EventFrameAttributeTemplate', 'Lookup', ['LookupId'], ['LookupId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__Lookup$CanBeUsedIn$EventFrameAttributeTemplate', 'EventFrameAttributeTemplate', type_='foreignkey')
    op.drop_constraint('FK__UnitOfMeasurement$CanBeUsedIn$EventFrameAttributeTemplate', 'EventFrameAttributeTemplate', type_='foreignkey')
    op.drop_column('EventFrameAttributeTemplate', 'UnitOfMeasurementId')
    op.drop_column('EventFrameAttributeTemplate', 'LookupId')
    # ### end Alembic commands ###
