"""empty message

Revision ID: c850b9555b12
Revises: 848984e66305
Create Date: 2018-01-01 15:28:58.286435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c850b9555b12'
down_revision = '848984e66305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EventFrame', 'Name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EventFrame', 'Name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###
