"""empty message

Revision ID: e3249c6eab5c
Revises: f7acf6303499
Create Date: 2019-02-13 07:59:48.503293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3249c6eab5c'
down_revision = 'f7acf6303499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Element', 'IsManaged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Element', sa.Column('IsManaged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
