"""empty message

Revision ID: ee9cffa206dc
Revises: 
Create Date: 2017-12-15 14:14:12.457273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9cffa206dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Enterprise',
    sa.Column('EnterpriseId', sa.Integer(), nullable=False),
    sa.Column('Abbreviation', sa.String(length=10), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('EnterpriseId'),
    sa.UniqueConstraint('Abbreviation'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('UnitOfMeasurement',
    sa.Column('UnitOfMeasurementId', sa.Integer(), nullable=False),
    sa.Column('Abbreviation', sa.String(length=15), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('UnitOfMeasurementId')
    )
    op.create_table('Lookup',
    sa.Column('LookupId', sa.Integer(), nullable=False),
    sa.Column('EnterpriseId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['EnterpriseId'], ['Enterprise.EnterpriseId'], ),
    sa.PrimaryKeyConstraint('LookupId')
    )
    op.create_table('Site',
    sa.Column('SiteId', sa.Integer(), nullable=False),
    sa.Column('Abbreviation', sa.String(length=10), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('EnterpriseId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['EnterpriseId'], ['Enterprise.EnterpriseId'], ),
    sa.PrimaryKeyConstraint('SiteId')
    )
    op.create_table('Area',
    sa.Column('AreaId', sa.Integer(), nullable=False),
    sa.Column('Abbreviation', sa.String(length=10), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('SiteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SiteId'], ['Site.SiteId'], ),
    sa.PrimaryKeyConstraint('AreaId'),
    sa.UniqueConstraint('Abbreviation'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('ElementTemplate',
    sa.Column('ElementTemplateId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('SiteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SiteId'], ['Site.SiteId'], ),
    sa.PrimaryKeyConstraint('ElementTemplateId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('LookupValue',
    sa.Column('LookupValueId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('LookupId', sa.Integer(), nullable=True),
    sa.Column('Value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LookupId'], ['Lookup.LookupId'], ),
    sa.PrimaryKeyConstraint('LookupValueId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('AttributeTemplate',
    sa.Column('AttributeTemplateId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('ElementTemplateId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], ),
    sa.PrimaryKeyConstraint('AttributeTemplateId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Element',
    sa.Column('ElementId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('ElementTemplateId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], ),
    sa.PrimaryKeyConstraint('ElementId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('EventFrameTemplate',
    sa.Column('EventFrameTemplateId', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('ElementTemplateId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('ParentEventFrameTemplateId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ElementTemplateId'], ['ElementTemplate.ElementTemplateId'], ),
    sa.ForeignKeyConstraint(['ParentEventFrameTemplateId'], ['EventFrameTemplate.EventFrameTemplateId'], ),
    sa.PrimaryKeyConstraint('EventFrameTemplateId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Tag',
    sa.Column('TagId', sa.Integer(), nullable=False),
    sa.Column('AreaId', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('LookupId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('UnitOfMeasurementId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AreaId'], ['Area.AreaId'], ),
    sa.ForeignKeyConstraint(['LookupId'], ['Lookup.LookupId'], ),
    sa.ForeignKeyConstraint(['UnitOfMeasurementId'], ['UnitOfMeasurement.UnitOfMeasurementId'], ),
    sa.PrimaryKeyConstraint('TagId')
    )
    op.create_table('ElementAttribute',
    sa.Column('ElementAttributeId', sa.Integer(), nullable=False),
    sa.Column('AttributeTemplateId', sa.Integer(), nullable=True),
    sa.Column('ElementId', sa.Integer(), nullable=True),
    sa.Column('TagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AttributeTemplateId'], ['AttributeTemplate.AttributeTemplateId'], ),
    sa.ForeignKeyConstraint(['ElementId'], ['Element.ElementId'], ),
    sa.ForeignKeyConstraint(['TagId'], ['Tag.TagId'], ),
    sa.PrimaryKeyConstraint('ElementAttributeId')
    )
    op.create_table('EventFrame',
    sa.Column('EventFrameId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('StartTime', sa.DateTime(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=True),
    sa.Column('ParentEventFrameId', sa.Integer(), nullable=True),
    sa.Column('EventFrameTemplateId', sa.Integer(), nullable=True),
    sa.Column('Order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EventFrameTemplateId'], ['EventFrameTemplate.EventFrameTemplateId'], ),
    sa.ForeignKeyConstraint(['ParentEventFrameId'], ['EventFrame.EventFrameId'], ),
    sa.PrimaryKeyConstraint('EventFrameId'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('Order')
    )
    op.create_table('TagValue',
    sa.Column('TagValueId', sa.Integer(), nullable=False),
    sa.Column('TagId', sa.Integer(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['TagId'], ['Tag.TagId'], ),
    sa.PrimaryKeyConstraint('TagValueId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagValue')
    op.drop_table('EventFrame')
    op.drop_table('ElementAttribute')
    op.drop_table('Tag')
    op.drop_table('EventFrameTemplate')
    op.drop_table('Element')
    op.drop_table('AttributeTemplate')
    op.drop_table('LookupValue')
    op.drop_table('ElementTemplate')
    op.drop_table('Area')
    op.drop_table('Site')
    op.drop_table('Lookup')
    op.drop_table('UnitOfMeasurement')
    op.drop_table('Enterprise')
    # ### end Alembic commands ###
