"""Event Frame Template View Selectable.

Revision ID: f3e927cc7144
Revises: b13236977763
Create Date: 2020-08-16 11:13:27.239643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'f3e927cc7144'
down_revision = 'b13236977763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventFrameTemplateView', sa.Column('Selectable', sa.Boolean(), nullable=True))
    # Set any existing Event Frame Template Views to Selectable.
    metadata = sa.MetaData()
    metadata.reflect(bind = op.get_bind())
    eventFrameTemplateViewTable = metadata.tables["EventFrameTemplateView"]
    updateStatement = eventFrameTemplateViewTable.update().values(Selectable = True)
    op.get_bind().execute(updateStatement)
    # Alter Selectable column to prevent null. 
    op.alter_column('EventFrameTemplateView', 'Selectable', existing_type=mysql.TINYINT(display_width=1), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventFrameTemplateView', 'Selectable')
    # ### end Alembic commands ###
