"""Messages and Notifications.

Revision ID: fa707933be8d
Revises: 454245852031
Create Date: 2019-04-24 20:34:53.859963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'fa707933be8d'
down_revision = '454245852031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('MessageId', sa.Integer(), nullable=False),
    sa.Column('Body', sa.Text(), nullable=False),
    sa.Column('RecipientId', sa.Integer(), nullable=False),
    sa.Column('SenderId', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RecipientId'], ['User.UserId'], name='FK__User$Receive$Message'),
    sa.ForeignKeyConstraint(['SenderId'], ['User.UserId'], name='FK__User$Send$Message'),
    sa.PrimaryKeyConstraint('MessageId')
    )
    op.create_index('IX__RecipientId__Timestamp', 'Message', ['RecipientId', 'Timestamp'], unique=False)
    op.create_table('Notification',
    sa.Column('NotificationId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=False),
    sa.Column('Payload', sa.Text(), nullable=True),
    sa.Column('UnixTimestamp', mysql.DOUBLE(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], name='FK__User$Have$Notification'),
    sa.PrimaryKeyConstraint('NotificationId')
    )
    op.create_index('IX__UserId__Name__UnixTimestamp', 'Notification', ['UserId', 'Name', 'UnixTimestamp'], unique=False)
    op.add_column('User', sa.Column('LastMessageReadTimestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'LastMessageReadTimestamp')
    # op.drop_index('IX__UserId__Name__UnixTimestamp', table_name='Notification')
    op.drop_table('Notification')
    # op.drop_index('IX__RecipientId__Timestamp', table_name='Message')
    op.drop_table('Message')
    # ### end Alembic commands ###
