-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 10:15:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BreweryPi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BreweryPi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BreweryPi` DEFAULT CHARACTER SET utf8 ;
USE `BreweryPi` ;

-- -----------------------------------------------------
-- Table `BreweryPi`.`Enterprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Enterprise` (
  `EnterpriseId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Abbreviation` VARCHAR(10) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EnterpriseId`),
  UNIQUE INDEX `AK_Enterprise_Name` (`Name` ASC),
  UNIQUE INDEX `AK_Enterprise_Abbreviation` (`Abbreviation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Site` (
  `SiteId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Abbreviation` VARCHAR(10) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `EnterpriseId` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SiteId`),
  UNIQUE INDEX `AK_Site_EnterpriseId_Name` (`EnterpriseId` ASC, `Name` ASC),
  INDEX `FK__Enterprise$Has$Site` (`EnterpriseId` ASC),
  UNIQUE INDEX `AK_Site_Abbreviation_EnterpriseId` (`Abbreviation` ASC, `EnterpriseId` ASC),
  CONSTRAINT `FK__Enterprise$Has$Site`
    FOREIGN KEY (`EnterpriseId`)
    REFERENCES `BreweryPi`.`Enterprise` (`EnterpriseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Area` (
  `AreaId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Abbreviation` VARCHAR(10) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `Name` VARCHAR(45) NOT NULL,
  `SiteId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AreaId`),
  UNIQUE INDEX `AK_Area_Name_SiteId` (`Name` ASC, `SiteId` ASC),
  INDEX `FK__Site$Has$Area` (`SiteId` ASC),
  UNIQUE INDEX `AK_Area_Abbreviation_SiteId` (`Abbreviation` ASC, `SiteId` ASC),
  CONSTRAINT `FK__Site$Has$Area`
    FOREIGN KEY (`SiteId`)
    REFERENCES `BreweryPi`.`Site` (`SiteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`UnitOfMeasurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`UnitOfMeasurement` (
  `UnitOfMeasurementId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Abbreviation` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UnitOfMeasurementId`),
  UNIQUE INDEX `AK_UnitOfMeasurement_Abbreviation_Name` (`Abbreviation` ASC, `Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`Lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Lookup` (
  `LookupId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EnterpriseId` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LookupId`),
  INDEX `FK__Enterprise$Has$Lookup_idx` (`EnterpriseId` ASC),
  UNIQUE INDEX `AK_Lookup_EnterpriseId_Name` (`EnterpriseId` ASC, `Name` ASC),
  CONSTRAINT `FK__Enterprise$Has$Lookup`
    FOREIGN KEY (`EnterpriseId`)
    REFERENCES `BreweryPi`.`Enterprise` (`EnterpriseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Tag` (
  `TagId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AreaId` INT UNSIGNED NOT NULL,
  `Description` VARCHAR(255) NULL,
  `LookupId` INT UNSIGNED NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UnitOfMeasurementId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TagId`),
  UNIQUE INDEX `AK_Tag_AreaId_Name` (`AreaId` ASC, `Name` ASC),
  INDEX `FK__UnitOfMeasurement$IsUsedIn$Tag` (`UnitOfMeasurementId` ASC),
  INDEX `FK__Area$Has$Tag` (`AreaId` ASC),
  INDEX `FK__Lookup$$Tag_idx` (`LookupId` ASC),
  CONSTRAINT `FK__UnitOfMeasurement$IsUsedIn$Tag`
    FOREIGN KEY (`UnitOfMeasurementId`)
    REFERENCES `BreweryPi`.`UnitOfMeasurement` (`UnitOfMeasurementId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK__Area$Has$Tag`
    FOREIGN KEY (`AreaId`)
    REFERENCES `BreweryPi`.`Area` (`AreaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK__Lookup$MayBeUsedIn$Tag`
    FOREIGN KEY (`LookupId`)
    REFERENCES `BreweryPi`.`Lookup` (`LookupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`TagValue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`TagValue` (
  `TagValueId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TagId` INT UNSIGNED NOT NULL,
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Value` FLOAT NOT NULL,
  PRIMARY KEY (`TagValueId`),
  UNIQUE INDEX `AK_TagValue_TagId_Timestamp` (`TagId` ASC, `Timestamp` ASC),
  INDEX `FK__Tag$Has$Value` (`TagId` ASC),
  CONSTRAINT `FK__Tag$Has$Value`
    FOREIGN KEY (`TagId`)
    REFERENCES `BreweryPi`.`Tag` (`TagId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`ElementTemplate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`ElementTemplate` (
  `ElementTemplateId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL,
  `Name` VARCHAR(45) NOT NULL,
  `SiteId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ElementTemplateId`),
  INDEX `FK__Site$Has$ElementTemplate` (`SiteId` ASC),
  UNIQUE INDEX `AK_ElementTemplate_Name_SiteId` (`SiteId` ASC, `Name` ASC),
  CONSTRAINT `FK__Site$Has$ElementTemplate`
    FOREIGN KEY (`SiteId`)
    REFERENCES `BreweryPi`.`Site` (`SiteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`Element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`Element` (
  `ElementId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL,
  `ElementTemplateId` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ElementId`),
  INDEX `FK__ElementTemplate$Has$Element` (`ElementTemplateId` ASC),
  UNIQUE INDEX `AK_Element_Name_ElementTemplateId` (`ElementTemplateId` ASC, `Name` ASC),
  CONSTRAINT `FK__ElementTemplate$Has$Element`
    FOREIGN KEY (`ElementTemplateId`)
    REFERENCES `BreweryPi`.`ElementTemplate` (`ElementTemplateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`AttributeTemplate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`AttributeTemplate` (
  `AttributeTemplateId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL,
  `ElementTemplateId` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AttributeTemplateId`),
  INDEX `FK__ElementTemplate$Has$AttributeTemplate` (`ElementTemplateId` ASC),
  UNIQUE INDEX `AK_AttributeTemplate_ElementTemplateId_Name` (`ElementTemplateId` ASC, `Name` ASC),
  CONSTRAINT `FK__ElementTemplate$Has$AttributeTemplate`
    FOREIGN KEY (`ElementTemplateId`)
    REFERENCES `BreweryPi`.`ElementTemplate` (`ElementTemplateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`ElementAttribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`ElementAttribute` (
  `ElementAttributeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AttributeTemplateId` INT UNSIGNED NOT NULL,
  `ElementId` INT UNSIGNED NOT NULL,
  `TagId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ElementAttributeId`),
  INDEX `FK__AttributeTemplate$IsUsedIn$ElementAttribute` (`AttributeTemplateId` ASC),
  INDEX `FK__Element$IsUsedIn$ElementAttribute` (`ElementId` ASC),
  INDEX `FK__Tag$IsUsedIn$ElementAttribute` (`TagId` ASC),
  UNIQUE INDEX `AK_ElementAttribute_AttributeTemplateId_ElementId` (`AttributeTemplateId` ASC, `ElementId` ASC),
  CONSTRAINT `FK__AttributeTemplate$IsUsedIn$ElementAttribute`
    FOREIGN KEY (`AttributeTemplateId`)
    REFERENCES `BreweryPi`.`AttributeTemplate` (`AttributeTemplateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK__Element$IsUsedIn$ElementAttribute`
    FOREIGN KEY (`ElementId`)
    REFERENCES `BreweryPi`.`Element` (`ElementId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK__Tag$IsUsedIn$ElementAttribute`
    FOREIGN KEY (`TagId`)
    REFERENCES `BreweryPi`.`Tag` (`TagId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreweryPi`.`LookupValue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreweryPi`.`LookupValue` (
  `LookupValueId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LookupId` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LookupValueId`),
  INDEX `FK__Lookup$Has$LookupValue_idx` (`LookupId` ASC),
  UNIQUE INDEX `AK_LookupValue_LookupId_Name` (`LookupId` ASC, `Name` ASC),
  CONSTRAINT `FK__Lookup$Has$LookupValue`
    FOREIGN KEY (`LookupId`)
    REFERENCES `BreweryPi`.`Lookup` (`LookupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
